[CmdletBinding()]
param(
    [string]$ToolShedUrl = "https://toolshed.g2.bx.psu.edu",
    [string]$SelectionPath,
    [string]$OutputPath,
    [string]$MetadataPath
)

$ErrorActionPreference = "Stop"

if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot "..\tool_list.yml"
}
if (-not $MetadataPath) {
    $MetadataPath = Join-Path $PSScriptRoot "..\tool_list.metadata.json"
}
if (-not $SelectionPath) {
    $SelectionPath = Join-Path $PSScriptRoot "..\tools.selected.json"
}

function ConvertTo-Array {
    param([object]$Value)
    if ($null -eq $Value) {
        return @()
    }
    if ($Value -is [System.Array]) {
        return $Value
    }
    return @($Value)
}

function Get-Repository {
    param(
        [string]$Name,
        [string]$Owner
    )

    $uri = "{0}/api/repositories?name={1}" -f $ToolShedUrl.TrimEnd("/"), [uri]::EscapeDataString($Name)
    $result = Invoke-RestMethod -Uri $uri -UseBasicParsing
    $matches = ConvertTo-Array $result | Where-Object {
        ($_.name -eq $Name) -and (($_.owner -eq $Owner) -or ($_.repo_owner_username -eq $Owner))
    }

    if (-not $matches) {
        throw "Tool Shed repository not found: $Owner/$Name"
    }

    return $matches | Select-Object -First 1
}

function Get-LatestMetadata {
    param([string]$RepositoryId)

    $uri = "{0}/api/repositories/{1}/metadata" -f $ToolShedUrl.TrimEnd("/"), $RepositoryId
    $metadata = Invoke-RestMethod -Uri $uri -UseBasicParsing
    $entries = foreach ($property in $metadata.PSObject.Properties) {
        $entry = $property.Value
        if ($entry.downloadable -and -not $entry.malicious) {
            [pscustomobject]@{
                NumericRevision = [int]$entry.numeric_revision
                Revision = [string]$entry.changeset_revision
                Tools = (ConvertTo-Array $entry.tools)
            }
        }
    }

    $latest = $entries | Sort-Object NumericRevision -Descending | Select-Object -First 1
    if (-not $latest) {
        throw "No downloadable revision found for repository id $RepositoryId"
    }
    return $latest
}

function Get-ToolVersions {
    param([object[]]$Tools)

    $versions = $Tools |
        ForEach-Object { $_.version } |
        Where-Object { $_ } |
        Sort-Object -Unique

    if ($versions) {
        return ($versions -join ", ")
    }
    return ""
}

function Read-SelectedRepositories {
    param([string]$Path)

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    if (-not (Test-Path $fullPath)) {
        throw "Tool selection file not found: $fullPath"
    }

    $items = ConvertTo-Array ((Get-Content -Raw -Encoding UTF8 $fullPath) | ConvertFrom-Json)
    $deduped = @{}
    foreach ($item in $items) {
        if (-not $item.name -or -not $item.owner) {
            continue
        }
        $key = ("{0}/{1}" -f $item.owner, $item.name).ToLowerInvariant()
        if (-not $deduped.ContainsKey($key)) {
            $section = if ($item.section) { [string]$item.section } else { "Tools" }
            $deduped[$key] = [pscustomobject]@{
                Name = [string]$item.name
                Owner = [string]$item.owner
                Section = $section
            }
        }
    }

    $repositories = $deduped.Values | Sort-Object Owner, Name
    if (-not $repositories) {
        return @()
    }
    return $repositories
}

$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
$resolved = @()
$repositories = Read-SelectedRepositories -Path $SelectionPath

foreach ($repo in $repositories) {
    Write-Host ("Resolving {0}/{1}" -f $repo.Owner, $repo.Name)
    $repository = Get-Repository -Name $repo.Name -Owner $repo.Owner
    $latest = Get-LatestMetadata -RepositoryId $repository.id
    $resolved += [pscustomobject]@{
        Name = $repo.Name
        Owner = $repo.Owner
        Section = $repo.Section
        RepositoryId = $repository.id
        Revision = $latest.Revision
        NumericRevision = $latest.NumericRevision
        ToolVersions = Get-ToolVersions -Tools $latest.Tools
        ToolShedUrl = $ToolShedUrl.TrimEnd("/")
        RepositoryUpdated = $repository.update_time
        Description = $repository.description
    }
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("# Generated by scripts/Update-ToolList.ps1")
[void]$builder.AppendLine("# Generated at: $generatedAt")
[void]$builder.AppendLine("# Tool Shed: $($ToolShedUrl.TrimEnd('/'))")
[void]$builder.AppendLine("install_resolver_dependencies: true")
[void]$builder.AppendLine("install_tool_dependencies: false")
[void]$builder.AppendLine("install_repository_dependencies: true")
[void]$builder.AppendLine("tools:")

foreach ($repo in $resolved) {
    [void]$builder.AppendLine("  - name: $($repo.Name)")
    [void]$builder.AppendLine("    owner: $($repo.Owner)")
    [void]$builder.AppendLine("    tool_shed_url: $($repo.ToolShedUrl)")
    [void]$builder.AppendLine("    revisions:")
    [void]$builder.AppendLine("      - '$($repo.Revision)'")
    [void]$builder.AppendLine("    tool_panel_section_label: '$($repo.Section)'")
}

$outputFullPath = [System.IO.Path]::GetFullPath($OutputPath)
$metadataFullPath = [System.IO.Path]::GetFullPath($MetadataPath)

$outputDirectory = Split-Path -Parent $outputFullPath
if ($outputDirectory -and -not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

[System.IO.File]::WriteAllText($outputFullPath, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
$metadataJson = if ($resolved) { $resolved | ConvertTo-Json -Depth 8 } else { "[]" }
[System.IO.File]::WriteAllText($metadataFullPath, $metadataJson + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $outputFullPath"
Write-Host "Wrote $metadataFullPath"
